# Generated by Django 3.0.14 on 2021-09-14 15:03

from django.db import migrations, models
import invoice_payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_payment', '0002_auto_20210913_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='currency_code',
            field=models.CharField(db_column='CurrencyCode', default=invoice_payment.models.get_default_currency, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='currency_rcp_code',
            field=models.CharField(db_column='CurrencyRcpCode', default=invoice_payment.models.get_default_currency, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency_code',
            field=models.CharField(db_column='CurrencyCode', default=invoice_payment.models.get_default_currency, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency_rcp_code',
            field=models.CharField(db_column='CurrencyRcpCode', default=invoice_payment.models.get_default_currency, max_length=255),
        ),
    ]
