# Generated by Django 3.0.14 on 2021-09-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_payment', '0003_auto_20210914_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='amount_net',
            field=models.DecimalField(db_column='AmountNet', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='amount_total',
            field=models.DecimalField(db_column='AmountTotal', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='historicalinvoicelineitem',
            name='amount_net',
            field=models.DecimalField(db_column='AmountNet', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='historicalinvoicelineitem',
            name='discount',
            field=models.DecimalField(db_column='Discount', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='historicalinvoicelineitem',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', default=0.0),
        ),
        migrations.AlterField(
            model_name='historicalinvoicelineitem',
            name='unit_price',
            field=models.DecimalField(db_column='UnitPrice', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_net',
            field=models.DecimalField(db_column='AmountNet', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_total',
            field=models.DecimalField(db_column='AmountTotal', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='amount_net',
            field=models.DecimalField(db_column='AmountNet', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='discount',
            field=models.DecimalField(db_column='Discount', decimal_places=2, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.IntegerField(db_column='Quantity', default=0.0),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(db_column='UnitPrice', decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
