# Generated by Django 3.0.14 on 2021-09-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210919_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'validated'), (2, 'payed'), (3, 'cancelled'), (4, 'deleted')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceevent',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'message'), (1, 'status'), (2, 'warning'), (3, 'payment'), (4, 'payment_error')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='historicalinvoicepayment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'accepted'), (2, 'refunded')], db_column='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'validated'), (2, 'payed'), (3, 'cancelled'), (4, 'deleted')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='invoiceevent',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'message'), (1, 'status'), (2, 'warning'), (3, 'payment'), (4, 'payment_error')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'accepted'), (2, 'refunded')], db_column='Status'),
        ),
    ]
