# Generated by Django 3.0.14 on 2021-09-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210926_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'validated'), (2, 'payed'), (3, 'cancelled'), (4, 'deleted'), (5, 'suspended')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='historicalinvoicepayment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'accepted'), (2, 'refunded'), (3, 'cancelled')], db_column='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'draft'), (1, 'validated'), (2, 'payed'), (3, 'cancelled'), (4, 'deleted'), (5, 'suspended')], db_column='Status', default=0),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'rejected'), (1, 'accepted'), (2, 'refunded'), (3, 'cancelled')], db_column='Status'),
        ),
    ]
