# Generated by Django 3.0.14 on 2021-10-18 10:30

import core.fields
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_bill_billevent_billitem_billpayment_historicalbill_historicalbillevent_historicalbillitem_historical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_invoice',
        ),
        migrations.RemoveField(
            model_name='historicalbill',
            name='date_invoice',
        ),
        migrations.AddField(
            model_name='bill',
            name='date_bill',
            field=core.fields.DateField(db_column='DateBill', default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='historicalbill',
            name='date_bill',
            field=core.fields.DateField(db_column='DateBill', default=datetime.date.today, null=True),
        ),
    ]
