# Generated by Django 3.2.16 on 2024-05-06 14:36

from django.db import migrations

from core.utils import insert_role_right_for_system, remove_role_right_for_system

REPORT_BILL_DETAILS_RIGHT = 131233
SYSTEM_ROLE = 64


def add_nhia_report_rights(apps, schema_editor):
    """
    Add bill details report rights to the IMIS Administrator.
    """
    insert_role_right_for_system(SYSTEM_ROLE, REPORT_BILL_DETAILS_RIGHT)


def remove_nhia_reports_rights(apps, schema_editor):
    """
    Remove bill details report rights to the IMIS Administrator.
    """
    remove_role_right_for_system(SYSTEM_ROLE, REPORT_BILL_DETAILS_RIGHT)


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20230126_0903'),
    ]

    operations = [
        migrations.RunPython(add_nhia_report_rights, remove_nhia_reports_rights),

    ]
