# Generated by Django 3.0.14 on 2021-10-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20211020_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpayment',
            name='code_sdr',
        ),
        migrations.RemoveField(
            model_name='historicalbillpayment',
            name='code_sdr',
        ),
    ]
