# Generated by Django 4.2.29 on 2026-09-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoice', '0015_alter_bill_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentinvoice',
            name='party_id',
            field=models.CharField(blank=True, db_column='PartyId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinvoice',
            name='party_type',
            field=models.ForeignKey(blank=True, db_column='PartyType', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalpaymentinvoice',
            name='payment_destination_id',
            field=models.CharField(blank=True, db_column='PaymentDestinationId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaymentinvoice',
            name='payment_destination_type',
            field=models.ForeignKey(blank=True, db_column='PaymentDestinationType', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='party_id',
            field=models.CharField(blank=True, db_column='PartyId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='party_type',
            field=models.ForeignKey(blank=True, db_column='PartyType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='party_type_invoice_payment', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='payment_destination_id',
            field=models.CharField(blank=True, db_column='PaymentDestinationId', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='payment_destination_type',
            field=models.ForeignKey(blank=True, db_column='PaymentDestinationType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_destination_type_invoice_payment', to='contenttypes.contenttype'),
        ),
    ]
